test_color_name_to_hex (__main__.TestExercice) ... FAIL
test_compute_mse (__main__.TestExercice) ... FAIL
test_create_list (__main__.TestExercice) ... ok
test_list_to_dict (__main__.TestExercice) ... ok

======================================================================
FAIL: test_color_name_to_hex (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 39, in test_color_name_to_hex
    'Mauvaise reponse'
AssertionError: Lists differ: [[], []] != [[('blue', '#0000FF'), ('red', '#FF0000'), [172 chars]A')]]

First differing element 0:
[]
[('blue', '#0000FF'), ('red', '#FF0000'), [83 chars]FF')]

- [[], []]
+ [[('blue', '#0000FF'),
+   ('red', '#FF0000'),
+   ('green', '#008000'),
+   ('yellow', '#FFFF00'),
+   ('black', '#000000'),
+   ('white', '#FFFFFF')],
+  [('orange', '#FFA500'),
+   ('blue', '#0000FF'),
+   ('red', '#FF0000'),
+   ('brown', '#A52A2A')]] : Mauvaise reponse

======================================================================
FAIL: test_compute_mse (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 65, in test_compute_mse
    'Erreur dans le calcul des MSE'
AssertionError: {} != {'LR': 220.6, 'DNN': 14.0, 'RF': 1681.8}
- {}
+ {'DNN': 14.0, 'LR': 220.6, 'RF': 1681.8} : Erreur dans le calcul des MSE

----------------------------------------------------------------------
Ran 4 tests in 0.003s

FAILED (failures=2)
